# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c88786fd2f3b170233752122f0a22fef041671e4e81dcfa613d5e54527c0f90c1bdcfd7928716d32cc0734796606d6132bdc546a0cd05b8183036470d1af3c2b

test:
  secret_key_base: bf52f0d4926e9f804dc884567719ff198a419678b4950070e9dfcbc74f207831250877a8837327cf6b0239fdecf3f93ea2e27fc8286dbaf1780ce82570ae18ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
